name: Get Issue list using CLI
on:
  workflow_dispatch:
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh issue list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
