name: Get issue list using CLI

on:
  # schedule:
  #- cron: "0/30 * * * * "
  workflow_dispatch:
env:
  INCOMING_WEBHOOK_URL: "${{secrets.INCOMING_WEBHOOK_INCIDENT_CHANNEL}}"
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  notify-incident-ticket-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get active variable
        id: activeissues
        uses: actions/checkout@v3
      - run:   
         echo::set-output name=IDTOKEN::$(gh issue list --label "Incident" --label "Active" --json "url" | jq -r '.url')
         echo $IDTOKEN
          
      - name: check output
        run: 
          echo "*NPM  Active Incident List*\n${{ steps.activeissues.outputs.IDTOKEN }}} "
          
          
