name: Get Issue list using CLI
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          active_issue_list = gh issue list --label "Incident" --label "Active"
          echo "$active_issue_list"

