name: Get issue list using CLI

on:
  # schedule:
  #- cron: "0/30 * * * * "
  workflow_dispatch:
env:
  INCOMING_WEBHOOK_URL: "${{secrets.INCOMING_WEBHOOK_INCIDENT_CHANNEL}}"
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  notify-incident-ticket-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get active variable
        id: activeissues
        uses: actions/checkout@v3
      - run:   
         echo "active_issue_list=$(gh issue list --label "Incident" --label "Active" --json "url" | jq '.[] | .url')" >> $GITHUB_ENV
          
      - name: check output
        run:     
          echo "*NPM  Active Incident List*\n${{ env.active_issue_list }} "
          
          
