name: Get issue list using CLI

on:
  # schedule:
  #- cron: "0/30 * * * * "
  workflow_dispatch:
env:
  INCOMING_WEBHOOK_URL: "${{secrets.INCOMING_WEBHOOK_INCIDENT_CHANNEL}}"
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  notify-incident-ticket-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get active variable
        id: step_1
        uses: actions/checkout@v3
      - run: 
           active_issue_list=$(gh issue list --label "Incident" --label "Active")
           echo $active_issue_list
           echo "*********************HEY********"
           #echo "$(active_issue_list | jq -r '.url')"

          
      - name: check output
        run: 
          echo "*NPM  Active Incident List*\n${{env.active_issue_list}}"
          
          
