name: Comment when opened
on:
  workflow_dispatch:
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: numOpenIssues= "$(gh issue list)"
              echo 'NUM_OPEN_ISSUES='$numOpenIssues
          
    
