name: Get issue list using CLI

on:
  # schedule:
  #- cron: "0/30 * * * * "
  workflow_dispatch:
env:
  INCOMING_WEBHOOK_URL: "${{secrets.INCOMING_WEBHOOK_INCIDENT_CHANNEL}}"
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  notify-incident-ticket-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get active variable
        id: get_active_issue_list
        uses: actions/checkout@v3
      - run: |
          gh issue list --label "Incident" --label "Active" >> $GITHUB_OUTPUT
 
          
      - name: check output
        run: echo "${{ jobs.get_active_issue_list.outputs }}"
