name: "Issue Labeler"
on:
  issues:
    types: [opened, edited, closed, reopened]
    if: >-
      contains(github.event.issue.labels.*.name, 'Incident')   |
      contains(github.event.issue.labels.*.name, 'incident-repair') 
jobs:
  add-incident-active-label:
    runs-on: ubuntu-latest
    steps:
    - uses: andymckay/labeler@master
      if: |
        contains(github.event.issue.labels.*.name, 'Incident') &&  (github.event.action == 'opened' || github.event.action == 'reopened')
      with:
          add-labels: "Active"
          remove-labels: "Closed"
  remove-incident-active-label:
    runs-on: ubuntu-latest
    steps:
    - uses: andymckay/labeler@master
      if: |
        contains(github.event.issue.labels.*.name, 'Incident') &&  github.event.action == 'closed'
      with:
          add-labels: "Closed"
          remove-labels: "Active"
  
